import '../models/author.dart';
import '../models/book.dart';

// Вымышленные учебные данные. ISBN приведены для примера,
// годы и издательства не описывают реальные издания.
// Ключи справочников используются в genreIds и publisherId.
const Map<int, String> seedGenres = {
  1: 'Роман',
  2: 'Приключения',
  3: 'Детектив',
  4: 'Фантастика',
  5: 'Детская литература',
  6: 'Научно-популярная литература',
};

const Map<int, String> seedPublishers = {
  1: 'Книжный дом',
  2: 'Литера',
  3: 'Горизонт',
  4: 'Мир знаний',
};

const List<Author> seedAuthors = [
  Author(
    id: 1,
    firstName: 'Иван',
    lastName: 'Соколов',
    country: 'Россия',
    birthYear: 1970,
  ),
  Author(
    id: 2,
    firstName: 'Анна',
    lastName: 'Морозова',
    country: 'Россия',
    birthYear: 1984,
  ),
  Author(
    id: 3,
    firstName: 'Оливер',
    lastName: 'Рид',
    country: 'Великобритания',
    birthYear: 1965,
  ),
  Author(
    id: 4,
    firstName: 'Эмма',
    lastName: 'Мартен',
    country: 'Франция',
    birthYear: 1978,
  ),
  Author(
    id: 5,
    firstName: 'Лукас',
    lastName: 'Вебер',
    country: 'Германия',
    birthYear: 1980,
  ),
  Author(
    id: 6,
    firstName: 'София',
    lastName: 'Росси',
    country: 'Италия',
    birthYear: 1990,
  ),
  Author(
    id: 7,
    firstName: 'Харуки',
    lastName: 'Танака',
    country: 'Япония',
    birthYear: 1973,
  ),
  Author(
    id: 8,
    firstName: 'Джеймс',
    lastName: 'Миллер',
    country: 'США',
    birthYear: 1987,
  ),
];

const List<Book> seedBooks = [
  Book(
    id: 1,
    title: 'Дом у реки',
    isbn: '9780000000019',
    year: 1998,
    pages: 240,
    publisherId: 1,
    authorIds: [1],
    genreIds: [1],
    copiesTotal: 5,
    copiesAvailable: 3,
  ),
  Book(
    id: 2,
    title: 'Зимняя дорога',
    isbn: '9780000000026',
    year: 2005,
    pages: 320,
    publisherId: 2,
    authorIds: [1],
    genreIds: [1, 2],
    copiesTotal: 4,
    copiesAvailable: 0,
  ),
  Book(
    id: 3,
    title: 'Письма из деревни',
    isbn: '9780000000033',
    year: 2012,
    pages: 180,
    publisherId: 3,
    authorIds: [1],
    genreIds: [1],
    copiesTotal: 3,
    copiesAvailable: 2,
  ),
  Book(
    id: 4,
    title: 'Тайна старой библиотеки',
    isbn: '9780000000040',
    year: 2016,
    pages: 280,
    publisherId: 2,
    authorIds: [2],
    genreIds: [3],
    copiesTotal: 6,
    copiesAvailable: 4,
  ),
  Book(
    id: 5,
    title: 'Последний ключ',
    isbn: '9780000000057',
    year: 2020,
    pages: 304,
    publisherId: 1,
    authorIds: [2],
    genreIds: [3],
    copiesTotal: 5,
    copiesAvailable: 1,
  ),
  Book(
    id: 6,
    title: 'Город за туманом',
    isbn: '9780000000064',
    year: 2023,
    pages: 352,
    publisherId: 4,
    authorIds: [2],
    genreIds: [3, 4],
    copiesTotal: 4,
    copiesAvailable: 4,
  ),
  Book(
    id: 7,
    title: 'Остров семи ветров',
    isbn: '9780000000071',
    year: 1995,
    pages: 224,
    publisherId: 3,
    authorIds: [3],
    genreIds: [2],
    copiesTotal: 7,
    copiesAvailable: 5,
  ),
  Book(
    id: 8,
    title: 'Путь через океан',
    isbn: '9780000000088',
    year: 2008,
    pages: 368,
    publisherId: 4,
    authorIds: [3],
    genreIds: [2],
    copiesTotal: 3,
    copiesAvailable: 0,
  ),
  Book(
    id: 9,
    title: 'Карта капитана',
    isbn: '9780000000095',
    year: 2019,
    pages: 256,
    publisherId: 1,
    authorIds: [3],
    genreIds: [2, 3],
    copiesTotal: 5,
    copiesAvailable: 2,
  ),
  Book(
    id: 10,
    title: 'Кафе на тихой улице',
    isbn: '9780000000101',
    year: 2001,
    pages: 192,
    publisherId: 2,
    authorIds: [4],
    genreIds: [1],
    copiesTotal: 4,
    copiesAvailable: 3,
  ),
  Book(
    id: 11,
    title: 'Летние письма',
    isbn: '9780000000118',
    year: 2014,
    pages: 208,
    publisherId: 3,
    authorIds: [4],
    genreIds: [1],
    copiesTotal: 6,
    copiesAvailable: 6,
  ),
  Book(
    id: 12,
    title: 'Звёздная станция',
    isbn: '9780000000125',
    year: 2007,
    pages: 416,
    publisherId: 4,
    authorIds: [5],
    genreIds: [4],
    copiesTotal: 8,
    copiesAvailable: 2,
  ),
  Book(
    id: 13,
    title: 'Сигнал с Марса',
    isbn: '9780000000132',
    year: 2021,
    pages: 288,
    publisherId: 1,
    authorIds: [5],
    genreIds: [4],
    copiesTotal: 5,
    copiesAvailable: 0,
  ),
  Book(
    id: 14,
    title: 'Сад маленьких чудес',
    isbn: '9780000000149',
    year: 2018,
    pages: 96,
    publisherId: 2,
    authorIds: [6],
    genreIds: [5],
    copiesTotal: 10,
    copiesAvailable: 7,
  ),
  Book(
    id: 15,
    title: 'Приключения рыжего кота',
    isbn: '9780000000156',
    year: 2022,
    pages: 112,
    publisherId: 3,
    authorIds: [6],
    genreIds: [2, 5],
    copiesTotal: 8,
    copiesAvailable: 6,
  ),
  Book(
    id: 16,
    title: 'Тишина бамбукового леса',
    isbn: '9780000000163',
    year: 1999,
    pages: 160,
    publisherId: 4,
    authorIds: [7],
    genreIds: [1],
    copiesTotal: 3,
    copiesAvailable: 1,
  ),
  Book(
    id: 17,
    title: 'Поезд к морю',
    isbn: '9780000000170',
    year: 2011,
    pages: 232,
    publisherId: 1,
    authorIds: [7],
    genreIds: [1, 2],
    copiesTotal: 4,
    copiesAvailable: 4,
  ),
  Book(
    id: 18,
    title: 'Как устроена погода',
    isbn: '9780000000187',
    year: 2017,
    pages: 144,
    publisherId: 2,
    authorIds: [8],
    genreIds: [6],
    copiesTotal: 6,
    copiesAvailable: 3,
  ),
  Book(
    id: 19,
    title: 'Мир под микроскопом',
    isbn: '9780000000194',
    year: 2024,
    pages: 176,
    publisherId: 3,
    authorIds: [8],
    genreIds: [6],
    copiesTotal: 7,
    copiesAvailable: 5,
  ),
  Book(
    id: 20,
    title: 'Экспедиция к звёздам',
    isbn: '9780000000200',
    year: 2025,
    pages: 336,
    publisherId: 4,
    authorIds: [5, 8],
    genreIds: [2, 4],
    copiesTotal: 5,
    copiesAvailable: 2,
  ),
];
